version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  prometheus:
    image: prom/prometheus
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
  app:
    build: .
  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./conf/wiremock:/home/wiremock
